apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-db
  labels:
    app: incident-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-db
  template:
    metadata:
      labels:
        app: incident-db
    spec:
      containers:
      - name: db
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: orders
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: incident-db
spec:
  ports:
  - port: 5432
  selector:
    app: incident-db
